
% Configuration____________________________________________________________
 


fielddata_matfile = '..\..\..\Hawkesbury\matlab\modeltools\matfiles\hawkesbury_all.mat';
fielddata = 'hawkesbury_all';

polygon_file = '..\..\..\Hawkesbury\matlab\modeltools\gis\HN_Calibration_v3.shp';


varname = {...
    'COND',...
    'ENT',...
    'FC',...
    'SAL',...
    'SED_GS_u22_9',...
    'SED_GS_u69_1',...
    'SED_ISO_C',...
    'SED_ISO_N',...
    'SED_MET_Fe',...
    'SED_MET_P',...
    'TEMP',...
    'WQ_CAR_PH',...
    'WQ_DIAG_ISO_del13CDOC_ppt',...
    'WQ_DIAG_ISO_del15NNOx',...
    'WQ_DIAG_ISO_del15NNOx_ppt',...
    'WQ_DIAG_ISO_del18ONOx',...
    'WQ_DIAG_OXY_SAT',...
    'WQ_DIAG_PHY_TCHLA',...
    'WQ_DIAG_PHY_TCHLA_EXO',...
    'WQ_DIAG_TOT_TDN',...
    'WQ_DIAG_TOT_TDP',...
    'WQ_DIAG_TOT_TKN',...
    'WQ_DIAG_TOT_TN',...
    'WQ_DIAG_TOT_TOC',...
    'WQ_DIAG_TOT_TP',...
    'WQ_DIAG_TOT_TSS',...
    'WQ_DIAG_TOT_TSS_MINERAL',...
    'WQ_DIAG_TOT_TSS_ORGANIC',...
    'WQ_DIAG_TOT_TURBIDITY',...
    'WQ_DIAG_TOT_TURBIDITY_EXO',...
    'WQ_NCS_SS1',...
    'WQ_NIT_AMM',...
    'WQ_OGM_DON',...
    'WQ_OGM_DOP',...
    'WQ_OGM_PON',...
    'WQ_OGM_fDOM',...
    'WQ_OXY_OXY',...
    'WQ_OXY_SAT',...
    'WQ_PHS_FRP',...
    'WQ_PHY_BGA_PE',...
    'WQ_SIL_RSI',...
    'spCOND',...
};


def.cAxis(1).value = [0 30];    %'WQ_NCS_SS1',...
def.cAxis(2).value = [0 150];    %'WQ_TRC_AGE',...
def.cAxis(3).value = [0 20];    %'WQ_OXY_OXY',...
def.cAxis(4).value = [0 10];	%'WQ_SIL_RSI',...
def.cAxis(5).value = [0 0.5];   %'WQ_NIT_AMM',...
def.cAxis(6).value = [0 150];     %'WQ_NIT_NIT',...
def.cAxis(7).value = [0 0.2];     %'WQ_PHS_FRP',...
def.cAxis(8).value = [0 10];   %'WQ_OGM_DOC',...
def.cAxis(9).value = [0 5];    %'WQ_OGM_POC',...
def.cAxis(10).value = [0 0.75];    %'WQ_OGM_DON',...
def.cAxis(11).value = [0 0.75];    %'WQ_OGM_PON',...
def.cAxis(12).value = [0 0.1];  %'WQ_OGM_DOP',...
def.cAxis(13).value = [0 0.2];  %'WQ_OGM_POP',...
def.cAxis(14).value = [0 10];  %'WQ_PHY_CYANO',...
def.cAxis(15).value = [0 20];    %'WQ_PHY_CHLOR',...
def.cAxis(16).value = [0 125];  %'WQ_PHY_CRYPT',...
def.cAxis(17).value = [0 2];  %'WQ_PHY_EDIAT',...
def.cAxis(18).value = [0 15];   %'WQ_PHY_LDIAT',...
def.cAxis(19).value = [0 150];   %'WQ_MAG_CGM',...
def.cAxis(20).value = [0 1];   %'WQ_BIV_FILTFRAC',...


plottype = 'timeseries'; %timeseries or 'profile'
%plottype = 'profile'; % or 'profile'

% Add field data to figure
plotvalidation = true; % true or false

plotdepth = {'surface';'bottom'};%;'bottom'};%'bottom'}; % Cell with either one or both
%plotdepth = {'surface'};%,'bottom'}; % Cell with either one or both

istitled = 1;
isylabel = 0;
islegend = 1;
isYlim = 0;
isRange = 1;
isRange_Bottom = 1;
Range_ALL = 1;
plotmodel = 0;
filetype = 'eps';
def.expected = 1; % plot expected WL
isFieldRange = 1;
fieldprctile = [10 90];

% ____________________________________________________________Configuration

% Models___________________________________________________________________


outputdirectory = 'D:\Cloud\Dropbox\Data_Hawkesbury\Field Data 2016 2018\';
% ____________________________________________________________Configuration

% Models___________________________________________________________________

 ncfile(1).name = 'I:\Hawkesbury\HN_Cal_v3_noIC\output\HN_Cal_2013_WQ.nc';
 ncfile(1).symbol = {'-';'--'};
 ncfile(1).colour = {[0.749019607843137 0.227450980392157 0.0039215686274509],[0.0509803921568627         0.215686274509804         0.968627450980392]}; % Surface and Bottom
 ncfile(1).legend = 'v11';
 ncfile(1).translate = 1;
%  
%  









% Defaults_________________________________________________________________



yr = 2016;
def.datearray = datenum(yr,01:06:37,01);
%def.datearray = datenum(yr,01:1:4,01);

def.dateformat = 'mm-yy';
% Must have same number as variable to plot & in same order

def.dimensions = [14 6]; % Width & Height in cm

def.dailyave = 0; % 1 for daily average, 0 for off. Daily average turns off smoothing.
def.smoothfactor = 3; % Must be odd number (set to 3 if none)

def.fieldsymbol = {'.','.'}; % Cell with same number of levels
def.fieldcolour = {'m',[0.6 0.6 0.6]}; % Cell with same number of levels

def.font = 'Arial';

def.xlabelsize = 7;
def.ylabelsize = 7;
def.titlesize = 12;
def.legendsize = 6;
def.legendlocation = 'northeastoutside';

def.visible = 'off'; % on or off
