clear all; close all;

plottfv_transect Hawkesbury_2017_WQ;
plottfv_transect Hawkesbury_2017_WQ_bottom;

plottfv_transect Hawkesbury_2013_WQ;
plottfv_transect Hawkesbury_2013_WQ_bottom;

plottfv_transect Hawkesbury_2014_WQ;
plottfv_transect Hawkesbury_2014_WQ_bottom;