% plottfv_transect SCERM_v6_2017_noaed
% plottfv_transect SCERM_v6_2017_noaed_bottom

% plottfv_transect SCERM_v6_2017_WQ
% plottfv_transect SCERM_v6_2017_WQ_bottom
% 
% plottfv_transect SCERM_v6_2015_WQ
% plottfv_transect SCERM_v6_2015_WQ_bottom

% plottfv_transect_StackedArea SCERM_v6_8_2017_stacked_area
% plottfv_transect_StackedArea SCERM_v6_8_2017_stacked_area_tchla
% plottfv_transect_StackedArea SCERM_V6_8_2017_stacked_area_tp
% 
% plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area
% plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_tchla
% plottfv_transect_StackedArea SCERM_V6_44_2017_stacked_area_tp
% 
% plottfv_transect_StackedArea SCERM_v6_8_2015_stacked_area
% plottfv_transect_StackedArea SCERM_v6_8_2015_stacked_area_tchla
% plottfv_transect_StackedArea SCERM_V6_8_2015_stacked_area_tp
% 
% plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area
% plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla
% plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp


% Canning Stuff
%TN,TP,TCHLA,N:P,SAL, 

fid = fopen('broken_setup.txt','wt');

plottfv_transect SCERM_v6_2015_WQ_scenarios_canning
plottfv_transect SCERM_v6_2015_WQ_scenarios_canning_bottom
plottfv_transect SCERM_v6_2015_WQ_scenarios
plottfv_transect SCERM_v6_2015_WQ_scenarios_bottom

plottfv_transect SCERM_v6_2017_WQ_scenarios
plottfv_transect SCERM_v6_2017_WQ_scenarios_bottom
plottfv_transect SCERM_v6_2017_WQ_scenarios_canning
plottfv_transect SCERM_v6_2017_WQ_scenarios_canning_bottom

%_________________________________
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tracer_tp
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tracer_tp_canning

plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tracer
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tracer_canning

%_________________________________
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_canning
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla_canning
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp_canning


plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area
plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_canning
plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_tchla
plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_tchla_canning
plottfv_transect_StackedArea SCERM_V6_44_2017_stacked_area_tp
plottfv_transect_StackedArea SCERM_V6_44_2017_stacked_area_tp_canning

%_________________________________
plottfv_transect_StackedArea SCERM_v6_8_2017_stacked_area
plottfv_transect_StackedArea SCERM_v6_8_2017_stacked_area_canning
plottfv_transect_StackedArea SCERM_v6_8_2017_stacked_area_tchla
plottfv_transect_StackedArea SCERM_v6_8_2017_stacked_area_tchla_canning
plottfv_transect_StackedArea SCERM_V6_8_2017_stacked_area_tp
plottfv_transect_StackedArea SCERM_V6_8_2017_stacked_area_tp_canning

plottfv_transect_StackedArea SCERM_v6_8_2015_stacked_area
plottfv_transect_StackedArea SCERM_v6_8_2015_stacked_area_canning
plottfv_transect_StackedArea SCERM_v6_8_2015_stacked_area_tchla
plottfv_transect_StackedArea SCERM_v6_8_2015_stacked_area_tchla_canning
plottfv_transect_StackedArea SCERM_V6_8_2015_stacked_area_tp
plottfv_transect_StackedArea SCERM_V6_8_2015_stacked_area_tp_canning


%_________________________________
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_dry
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_canning_dry
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla_dry
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla_canning_dry
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp_dry
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp_canning_dry

%_________________________________
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_capped
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_canning_capped
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla_capped
plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla_canning_capped
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp_capped
plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp_canning_capped

%_________________________________
plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_wet
plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_canning_wet
plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_tchla_wet
plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_tchla_canning_wet
plottfv_transect_StackedArea SCERM_V6_44_2017_stacked_area_tp_wet
plottfv_transect_StackedArea SCERM_V6_44_2017_stacked_area_tp_canning_wet


% % 
% % plottfv_transect SCERM_v6_2017_WQ_canning
% % plottfv_transect SCERM_v6_2017_WQ_bottom_canning
% % 
% % plottfv_transect SCERM_v6_2015_WQ_canning
% % plottfv_transect SCERM_v6_2015_WQ_bottom_canning
% % 
% % 
% % plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_canning
% % plottfv_transect_StackedArea SCERM_v6_44_2015_stacked_area_tchla_canning
% % plottfv_transect_StackedArea SCERM_V6_44_2015_stacked_area_tp_canning
% % 
% % plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_canning
% % plottfv_transect_StackedArea SCERM_v6_44_2017_stacked_area_tchla_canning
% % plottfv_transect_StackedArea SCERM_V6_44_2017_stacked_area_tp_canning
% % 
% % % Senarios
% % 
% % % Quarterly Transect 5 - 7  8- 10  11 - 1 2 -4
% % 
% % plottfv_transect_StackedArea SCERM_V6_8_2015_stacked_area_tracer_tp
% % plottfv_transect_StackedArea SCERM_V6_8_2015_stacked_area_tracer
% % % 
% % % 
% % % 2015 Base Target Capped Dry
% % % 2017 Base Wet
% % % 
% % % plottfv_transect SCERM_v6_2017_WQ
% % % plottfv_transect SCERM_v6_2017_WQ_bottom
% % % 
% % % plottfv_transect SCERM_v6_2015_WQ
% % % plottfv_transect SCERM_v6_2015_WQ_bottom