clear all; close all;

addpath(genpath('functions'));

load swan.mat;

%load Oxy.mat;

%  headers = {...
%     'ISOTime',...
%     'wl',...
%     'Sal',...
%     'Temp',...
%     'TRACE_1',...
% 	'SS1',...
%     'SS2',...
%     'RET',...
%     'Oxy',...
%     'Sil',...
%     'Amm',...
%     'Nit',...
%     'FRP',...
% 	'FRP_ADS',...
%     'DOC',...
%     'POC',...
%     'DON',...
%     'PON',...
%     'DOP',...
%     'POP',...
% 	'DOCR',...
% 	'DONR',...
% 	'DOPR',...
% 	'CPOM',...
%     'GRN',...
%     'BGA',...
%     'CRYPT',...
%     'DIATOM',...
%     'DINO',...
%     };

 headers = {...
    'ISOTime',...
    'wl',...
    'Sal',...
    'Temp',...
    'TRACE_1',...
    'AGE',...
    'SS1',...
    'SS2',...
    'Oxy',...
    'Sil',...
    'Amm',...
    'Nit',...
    'FRP',...
	'FRP_ADS',...
    'DOC',...
    'POC',...
    'DON',...
    'PON',...
    'DOP',...
    'POP',...
	'DOCR',...
	'DONR',...
	'DOPR',...
	'CPOM',...
    'GRN',...
    'CRYPT',...
    'DIATOM',...
    'DINO',...
    'DINO_IN',...
    'BGA',...
    'BGA_RHO',...
    'BGA_IN',...
    'BGA_IP',...
};


% 
% 
% 
 datearray(:,1) = datenum(2008,01,01,00,00,00):60/(60*24):datenum(2020,01,01,00,00,00);
% 
% % 0 for no HD shift, 1 for shift
  create_interpolated_BC_for_inflow_NAR_v1(swan,headers,datearray,0);disp('NAR'); close all;
  create_interpolated_BC_for_inflow_Fremantle(swan,headers,datearray,0); disp('Fremantle');close all;
%    
%  

plot_bcfiles('BCs/Tide/')

clear headers;

 headers = {...
    'ISOTime',...
    'Flow',...
    'Sal',...
    'Temp',...
    'TRACE_1',...
    'AGE',...
    'SS1',...
    'SS2',...
    'Oxy',...
    'Sil',...
    'Amm',...
    'Nit',...
    'FRP',...
	'FRP_ADS',...
    'DOC',...
    'POC',...
    'DON',...
    'PON',...
    'DOP',...
    'POP',...
	'DOCR',...
	'DONR',...
	'DOPR',...
	'CPOM',...
    'GRN',...
    'CRYPT',...
    'DIATOM',...
    'DINO',...
    'DINO_IN',...
    'BGA',...
    'BGA_RHO',...
    'BGA_IN',...
    'BGA_IP',...
    };

% 
clear datearray;
 datearray(:,1) = datenum(2008,01,01,00,00,00):1:datenum(2020,01,01,00,00,00);
 
  create_interpolated_BC_for_inflow_Helena(swan,headers,datearray);   disp('Helena');close all;%DONE
  create_interpolated_BC_for_inflow_Bennet(swan,headers,datearray); disp('Bennet');close all;%DONE
% 
% % 
% 
% 
 create_interpolated_BC_for_inflow_Ellenbrook(swan,headers,datearray); disp('Ellenbrook');close all;
 create_interpolated_BC_for_inflow_Susannah(swan,headers,datearray);   disp('Susannah');close all;
 create_interpolated_BC_for_inflow_UpperSwan_2000(swan,headers,datearray);disp('UpperSwan');close all;

 create_interpolated_BC_for_inflow_Bayswater(swan,headers,datearray);disp('Bayswater');close all; %DONE
 create_interpolated_BC_for_inflow_Jane(swan,headers,datearray);disp('Jane');close all;
 create_interpolated_BC_for_inflow_Canning(swan,headers,datearray);disp('Canning');close all;
% 
% create_interpolated_oxygenation_plant_GFD(oxy,headers,datearray);disp('GFD Oxygenation Plants');close all;
% create_interpolated_oxygenation_plant_CAV(oxy,headers,datearray);disp('CAV Oxygenation Plants');close all;

plot_bcfiles('BCs/Flow/')



%create_interpolated_BC_for_inflow_Fremantle(swan,headers,datearray,shift_AHD)

