
 

% SITE Configuration_______________________________________________________
% fielddata_matfile = 'lowerlakes.mat';
% fielddata = 'lowerlakes';

fielddata_matfile = '/Projects2/busch_github/CDM/data/store/archive/cllmm.mat';
%fielddata = 'UA';
fielddata = 'cllmm';
polygon_file = '../../../CDM/gis/supplementary/Coorong/Coorong_obs_sites.shp';
%polygon_file = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/model/gis/shp/31_material_zones_names.shp';


%sites = [17,18,20];  % Sites in shapefile (polygon IDs) to plot
% ____________________________________________________________Configuration

% NCS_ss1
% TRC_age
% OXY_oxy
% SIL_rsi
% NIT_amm
% NIT_nit
% PHS_frp
% PHS_frp_ads
% OGM_doc
% OGM_poc
% OGM_don
% OGM_pon
% OGM_dop
% OGM_pop
% PHY_grn


% VAR Configuration________________________________________________________
varname = {...
'WQ_DIAG_PHY_TCHLA',...
'SAL',...
'TEMP',...
'WQ_DIAG_TOT_TN',...
'WQ_DIAG_TOT_TP',...
'WQ_DIAG_TOT_TOC',...
'WQ_OGM_DOC',...
'WQ_OGM_POC',...
'WQ_PHY_GRN',...
'WQ_PHY_CRYPT',...
'WQ_PHY_DIATOM',...
'WQ_PHY_DINO',...
'WQ_NIT_AMM',...
'WQ_NIT_NIT',...
'WQ_PHS_FRP',...
'WQ_PHS_FRP_ADS',...
'WQ_OGM_DON',...
'WQ_OGM_PON',...
'WQ_OGM_DOP',...
'WQ_OGM_POP',...
'WQ_DIAG_TOT_TSS',...
'WQ_DIAG_NIT_AMM_DSF',...
'WQ_DIAG_NIT_NIT_DSF',...
'WQ_DIAG_PHS_FRP_DSF',...
'WQ_DIAG_PHY_UPT_NO3',...
'WQ_DIAG_PHY_UPT_NH4',...
'WQ_DIAG_PHY_UPT_PO4',...
'WQ_NCS_SS1',...
'WQ_NCS_SS2',...
'WQ_NCS_SS3',...
'WQ_TRC_AGE',...
'WQ_OXY_OXY',...
'WQ_SIL_RSI',...
'WQ_DIAG_PHY_DIATOM_NTOP',...
'WQ_DIAG_PHY_DIATOM_FI',...
'WQ_DIAG_PHY_DIATOM_FNIT',...
'WQ_DIAG_PHY_DIATOM_FPHO',...
'WQ_DIAG_PHY_DIATOM_FSIL',...
'WQ_DIAG_PHY_DIATOM_FT',...
'WQ_DIAG_PHY_DIATOM_FSAL',...
'WQ_DIAG_PHY_DINO_NTOP',...
'WQ_DIAG_PHY_DINO_FI',...
'WQ_DIAG_PHY_DINO_FNIT',...
'WQ_DIAG_PHY_DINO_FPHO',...
'WQ_DIAG_PHY_DINO_FSIL',...
'WQ_DIAG_PHY_DINO_FT',...
'WQ_DIAG_PHY_DINO_FSAL',...
'WQ_DIAG_OGM_PON_HYD',...
'WQ_DIAG_OGM_POP_HYD',...
'WQ_DIAG_OGM_DOC_MIN',...
'WQ_DIAG_OGM_DON_MIN',...
'WQ_DIAG_OGM_DOP_MIN',...
'WQ_DIAG_PHY_DIATOM_GPP_C',...
'WQ_DIAG_PHY_DIATOM_RSP_C',...
'WQ_DIAG_PHY_DIATOM_EXC_C',...
'WQ_DIAG_PHY_DIATOM_MOR_C',...
'WQ_DIAG_PHY_DIATOM_SET_C',...
'WQ_DIAG_PHY_DIATOM_GPP_N',...
'WQ_DIAG_PHY_DIATOM_RSP_N',...
'WQ_DIAG_PHY_DIATOM_EXC_N',...
'WQ_DIAG_PHY_DIATOM_MOR_N',...
'WQ_DIAG_PHY_DIATOM_SET_N',...
'WQ_DIAG_PHY_DIATOM_GPP_P',...
'WQ_DIAG_PHY_DIATOM_RSP_P',...
'WQ_DIAG_PHY_DIATOM_EXC_P',...
'WQ_DIAG_PHY_DIATOM_MOR_P',...
'WQ_DIAG_PHY_DIATOM_SET_P',...
'WQ_DIAG_PHY_GRN_NTOP',...
'WQ_DIAG_PHY_GRN_FI',...
'WQ_DIAG_PHY_GRN_FNIT',...
'WQ_DIAG_PHY_GRN_FPHO',...
'WQ_DIAG_PHY_GRN_FSIL',...
'WQ_DIAG_PHY_GRN_FT',...
'WQ_DIAG_PHY_GRN_FSAL',...
'WQ_DIAG_PHY_GRN_GPP_C',...
'WQ_DIAG_PHY_GRN_RSP_C',...
'WQ_DIAG_PHY_GRN_EXC_C',...
'WQ_DIAG_PHY_GRN_MOR_C',...
'WQ_DIAG_PHY_GRN_SET_C',...
'WQ_DIAG_PHY_GRN_GPP_N',...
'WQ_DIAG_PHY_GRN_RSP_N',...
'WQ_DIAG_PHY_GRN_EXC_N',...
'WQ_DIAG_PHY_GRN_MOR_N',...
'WQ_DIAG_PHY_GRN_SET_N',...
'WQ_DIAG_PHY_GRN_GPP_P',...
'WQ_DIAG_PHY_GRN_RSP_P',...
'WQ_DIAG_PHY_GRN_EXC_P',...
'WQ_DIAG_PHY_GRN_MOR_P',...
'WQ_DIAG_PHY_GRN_SET_P',...
'WQ_DIAG_PHY_CRYPT_NTOP',...
'WQ_DIAG_PHY_CRYPT_FI',...
'WQ_DIAG_PHY_CRYPT_FNIT',...
'WQ_DIAG_PHY_CRYPT_FPHO',...
'WQ_DIAG_PHY_CRYPT_FSIL',...
'WQ_DIAG_PHY_CRYPT_FT',...
'WQ_DIAG_PHY_CRYPT_FSAL',...
'WQ_DIAG_PHY_CRYPT_GPP_C',...
'WQ_DIAG_PHY_CRYPT_RSP_C',...
'WQ_DIAG_PHY_CRYPT_EXC_C',...
'WQ_DIAG_PHY_CRYPT_MOR_C',...
'WQ_DIAG_PHY_CRYPT_SET_C',...
'WQ_DIAG_PHY_CRYPT_GPP_N',...
'WQ_DIAG_PHY_CRYPT_RSP_N',...
'WQ_DIAG_PHY_CRYPT_EXC_N',...
'WQ_DIAG_PHY_CRYPT_MOR_N',...
'WQ_DIAG_PHY_CRYPT_SET_N',...
'WQ_DIAG_PHY_CRYPT_GPP_P',...
'WQ_DIAG_PHY_CRYPT_RSP_P',...
'WQ_DIAG_PHY_CRYPT_EXC_P',...
'WQ_DIAG_PHY_CRYPT_MOR_P',...
'WQ_DIAG_PHY_CRYPT_SET_P',...
'WQ_DIAG_PHY_DINO_GPP_C',...
'WQ_DIAG_PHY_DINO_RSP_C',...
'WQ_DIAG_PHY_DINO_EXC_C',...
'WQ_DIAG_PHY_DINO_MOR_C',...
'WQ_DIAG_PHY_DINO_SET_C',...
'WQ_DIAG_PHY_DINO_GPP_N',...
'WQ_DIAG_PHY_DINO_RSP_N',...
'WQ_DIAG_PHY_DINO_EXC_N',...
'WQ_DIAG_PHY_DINO_MOR_N',...
'WQ_DIAG_PHY_DINO_SET_N',...
'WQ_DIAG_PHY_DINO_GPP_P',...
'WQ_DIAG_PHY_DINO_RSP_P',...
'WQ_DIAG_PHY_DINO_EXC_P',...
'WQ_DIAG_PHY_DINO_MOR_P',...
'WQ_DIAG_PHY_DINO_SET_P',...
'WQ_DIAG_PHY_SET',...
'WQ_DIAG_PHY_RES',...
'WQ_DIAG_PHY_TCHLA',...
'WQ_DIAG_PHY_IN',...
'WQ_DIAG_PHY_IP',...
'WQ_DIAG_PHY_GPP',...
'WQ_DIAG_PHY_NCP',...
'WQ_DIAG_PHY_UPT_DIC',...
'WQ_DIAG_PHY_PAR',...
'WQ_DIAG_PHY_TPHY',...
'WQ_DIAG_PHY_PPR',...
'WQ_DIAG_PHY_NPR',...
'WQ_DIAG_PHY_MPB_BEN',...
'WQ_DIAG_PHY_MPB_GPP',...
'WQ_DIAG_PHY_MPB_RSP',...
'WQ_DIAG_PHY_MPB_SWI',...
'WQ_DIAG_PHY_UPT_N2',...
'WQ_DIAG_SDF_FSED_OXY',...
'WQ_DIAG_SDF_FSED_DIC',...
'WQ_DIAG_SDF_FSED_AMM',...
'WQ_DIAG_SDF_FSED_NIT',...
'WQ_DIAG_SDF_FSED_FRP',...
'WQ_DIAG_SDF_FSED_POC',...
'WQ_DIAG_SDF_FSED_DOC',...
'WQ_DIAG_SDF_FSED_PON',...
'WQ_DIAG_SDF_FSED_DON',...
'WQ_DIAG_SDF_FSED_POP',...
'WQ_DIAG_SDF_FSED_DOP',...
'WQ_DIAG_MAC_PAR',...
'WQ_DIAG_MAC_GPP',...
'WQ_DIAG_MAC_NPP',...
'WQ_DIAG_MAC_MAC_BEN',...
'WQ_DIAG_MAC_MAC_LAI',...
'WQ_DIAG_MAC_MAC_AG',...
'WQ_DIAG_MAC_MAC_BG',...
'WQ_DIAG_MAC_MAC_ROOT_DEPTH',...
'WQ_DIAG_MAC_MAC_ROOT_O2',...
'WQ_DIAG_NCS_SS1_VVEL',...
'WQ_DIAG_NCS_SS1_SET',...
'WQ_DIAG_NCS_SS2_VVEL',...
'WQ_DIAG_NCS_SS2_SET',...
'WQ_DIAG_NCS_SS3_VVEL',...
'WQ_DIAG_NCS_SS3_SET',...
'WQ_DIAG_NCS_SS_SED',...
'WQ_DIAG_NCS_TAU_0',...
'WQ_DIAG_NCS_EPSILON',...
'WQ_DIAG_NCS_FS1',...
'WQ_DIAG_NCS_FS2',...
'WQ_DIAG_NCS_FS3',...
'WQ_DIAG_NCS_SET',...
'WQ_DIAG_NCS_SWI',...
'WQ_DIAG_NCS_SWI_DZ',...
'WQ_DIAG_NCS_RESUS',...
'WQ_DIAG_NCS_D_TAUB',...
'WQ_DIAG_OXY_SAT',...
'WQ_DIAG_OXY_OXY_DSF',...
'WQ_DIAG_OXY_OXY_ATM',...
'WQ_DIAG_OXY_OXY_DSFV',...
'WQ_DIAG_OXY_OXY_ATMV',...
'WQ_DIAG_SIL_DSF_RSI',...
'WQ_DIAG_NIT_NITRIF',...
'WQ_DIAG_NIT_DENIT',...
'WQ_DIAG_NIT_ANAMMOX',...
'WQ_DIAG_NIT_DNRA',...
'WQ_DIAG_NIT_DIN_ATM',...
'WQ_DIAG_PHS_FRP_ADS_SET',...
'WQ_DIAG_PHS_FRP_ADS_RES',...
'WQ_DIAG_PHS_FRP_ADS_SWI',...
'WQ_DIAG_PHS_FRP_SRP',...
'WQ_DIAG_PHS_DIP_ATM',...
'WQ_DIAG_OGM_POC_SET',...
'WQ_DIAG_OGM_PON_SET',...
'WQ_DIAG_OGM_POP_SET',...
'WQ_DIAG_OGM_OM_SED_FRAC',...
'WQ_DIAG_OGM_CDOM',...
'WQ_DIAG_OGM_TOC_SED',...
'WQ_DIAG_OGM_TON_SED',...
'WQ_DIAG_OGM_TOP_SED',...
'WQ_DIAG_OGM_POC_SWI',...
'WQ_DIAG_OGM_DOC_SWI',...
'WQ_DIAG_OGM_PON_SWI',...
'WQ_DIAG_OGM_DON_SWI',...
'WQ_DIAG_OGM_POP_SWI',...
'WQ_DIAG_OGM_DOP_SWI',...
'WQ_DIAG_OGM_POC_RES',...
'WQ_DIAG_OGM_PON_RES',...
'WQ_DIAG_OGM_POP_RES',...
'WQ_DIAG_OGM_POC_HYD',...
'WQ_DIAG_OGM_DOC_ANAEROBIC',...
'WQ_DIAG_OGM_DOC_DENIT',...
'WQ_DIAG_OGM_BOD5',...
'WQ_DIAG_OGM_POM_VVEL',...
'WQ_DIAG_OGM_DOC_FLOC',...
};

 def.cAxis(1).value = [0 150];   %'SAL',...
% def.cAxis(2).value = [5 35];  %'TEMP',...
% def.cAxis(3).value = [0 1];   %'RUPPIA_HSI',...
% def.cAxis(4).value = [0 10];   %'TN',...
% def.cAxis(5).value = [0 2];   %'TP',...
% def.cAxis(6).value = [0 50];   %'TCHLA',...
% def.cAxis(7).value = [0 0.2];         %'AMM',...
% def.cAxis(8).value = [0 2];         %'NIT',...
% def.cAxis(9).value = [0 0.4];         %'TP',...
% def.cAxis(10).value = [0 0.2];         %'FRP',...
% def.cAxis(11).value = [0 15];         %'OXY',...
% def.cAxis(12).value = [0 30];         %'TSS',...
% def.cAxis(13).value = [0 30];         %'TURB',...
% def.cAxis(14).value = [0 250];         %'WQ_PHY_GRN',...
% def.cAxis(15).value = [0 0.05];         % 'WQ_OGM_POP',...
% def.cAxis(16).value = [0 0.5];         %'WQ_OGM_DOP',...
% def.cAxis(17).value = [0 0.5];         %'WQ_OGM_PON',...
% def.cAxis(18).value = [0 5];         %'WQ_OGM_DON',...

%for vvvv=1:length(varname)
%def.cAxis(vvvv).value = [ ];
%end
%def.cAxis(3).value = [0 150];
% ____________________________________________________________Configuration

start_plot_ID = 1;
end_plot_ID = 1;
% PLOT Configuration_______________________________________________________
plottype = 'timeseries'; %timeseries or 'profile'

plotvalidation = true; % Add field data to figure (true or false)
plotmodel = 1;

plotdepth = {'surface'};  % Cell-array with either one or both
depth_range = [0.2 100];
validation_minmax = 0;

istitled = 1;
isylabel = 1;
islegend = 1;
isYlim   = 1;
isRange  = 0;
isRange_Bottom = 0;
Range_ALL = 0;

filetype = 'eps';
def.expected = 1; % plot expected WL

isFieldRange = 0;
fieldprctile = [10 90];

isHTML = 1;

yr = 2017;
def.datearray = datenum(yr,7:6:61,1);

%outputdirectory = './Timeseries_Basecase_June/RAW/';
%htmloutput = './Timeseries_Basecase_June/HTML/';
outputdirectory = '/Projects2/CDM/HCHB_scenario_assessment/MER_Coorong_eWater_2022_GEN15_newBC_testing/plots/eWater_2022_GEN15_newBC_sites/RAW/';
htmloutput = '/Projects2/CDM/HCHB_scenario_assessment/MER_Coorong_eWater_2022_GEN15_newBC_testing/plots/eWater_2022_GEN15_newBC_sites/HTML/';
% ____________________________________________________________Configuration





% Models___________________________________________________________________
  ncfile(1).name = '/Projects2/CDM/HCHB_scenario_assessment/MER_Coorong_eWater_2022_GEN15_newBC_testing/output_basecase/eWater2021_basecase_t3_all.nc';
  %'/Projects2/CDM/HCHB_scenario_assessment/MER_Coorong_eWater_2021_GEN15/output_basecase7/eWater2021_basecase_all.nc';
  ncfile(1).symbol = {'-';'--'};
  ncfile(1).colour = {[166,86,40]./255,[166,86,40]./255};% Surface and Bottom % Surface and Bottom
  ncfile(1).legend = 'CDM';
  ncfile(1).translate = 1;
 % 
% ncfile(1).name = '/Projects2/CDM/MER_Coorong_eWater_2021/output_basecase/eWater2021_basecase_all.nc';
% ncfile(1).symbol = {'-';'--'};
% ncfile(1).colour = {[77,175,74]./255,[77,175,74]./255}; % Surface and Bottom
% ncfile(1).legend = 'eWater-2021';
% ncfile(1).translate = 1;
 
% ncfile(2).name = '/Projects2/CDM/HCHB_scenario_assessment/MER_Coorong_eWater_2022_GEN15_newBC_testing/output_basecase/eWater2021_basecase_t3_newCSV_all.nc';
% ncfile(2).symbol = {'-';'--'};
% ncfile(2).colour = {[55,126,184]./255,[55,126,184]./255}; % Surface and Bottom
% ncfile(2).legend = 'newCSV';
% ncfile(2).translate = 1;
% % 
%  
%  ncfile(3).name = '/Projects2/CDM/HCHB_scenario_assessment/MER_Coorong_eWater_2021_GEN15_newBC/output_t4_2/eWater2021_basecase_t4_all.nc';
%  ncfile(3).symbol = {'-';'--'};
%  ncfile(3).colour = {[255,127,0]./255,[255,127,0]./255}; % Surface and Bottom
%  ncfile(3).legend = 't42';
%  ncfile(3).translate = 1;

% 
%  ncfile(5).name = '/Projects2/CDM/MER_Coorong_eWater_2021/output_Scen2/eWater2021_Scen2_all.nc';
%  ncfile(5).symbol = {'-';'--'};
%  ncfile(5).colour = {[255,127,0]./255,[255,127,0]./255}; % Surface and Bottom
%  ncfile(5).legend = 'No eWater 1yr';
%  ncfile(5).translate = 1;

% 
%  

% ___________________________________________________________________Models



% Defaults_________________________________________________________________

% Makes start date, end date and datetick array
%def.datearray = datenum(yr,0def.datearray = datenum(yr,01:4:36,01);
%def.datearray = datenum(yr,1:12:96,01);

% yr = 2012;
% def.datearray = datenum(yr,01:01:04,01);

def.dateformat = 'mm/yyyy';
% Must have same number as variable to plot & in same order

def.dimensions = [20 8]; % Width & Height in cm

def.dailyave = 0; % 1 for daily average, 0 for off. Daily average turns off smoothing.
def.smoothfactor = 3; % Must be odd number (set to 3 if none)

def.fieldsymbol = {'.','.'}; % Cell with same number of levels
def.fieldcolour = {'m',[0.6 0.6 0.6]}; % Cell with same number of levels

def.font = 'Arial';

def.xlabelsize = 7;
def.ylabelsize = 7;
def.titlesize = 10;
def.legendsize = 6;
def.legendlocation = 'northeastoutside';

def.visible = 'off'; % on or off
