
 

% SITE Configuration_______________________________________________________
% fielddata_matfile = 'lowerlakes.mat';
% fielddata = 'lowerlakes';

fielddata_matfile = '/Projects2/busch_github/CDM/data/store/archive/cllmm.mat';
%fielddata = 'UA';
fielddata = 'cllmm';
%polygon_file = '../../../CDM/gis/supplementary/Coorong/Coorong_obs_sites.shp';
%polygon_file = '../../../CDM/gis/supplementary/Coorong_IC_regions.shp';
polygon_file = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/model/gis/shp/31_material_zones_names.shp';

%sites = [17,18,20];  % Sites in shapefile (polygon IDs) to plot
% ____________________________________________________________Configuration

% NCS_ss1
% TRC_age
% OXY_oxy
% SIL_rsi
% NIT_amm
% NIT_nit
% PHS_frp
% PHS_frp_ads
% OGM_doc
% OGM_poc
% OGM_don
% OGM_pon
% OGM_dop
% OGM_pop
% PHY_grn

% VAR Configuration________________________________________________________
% varname = {...
%     'H'                            ,...
%     'V_x',...
% 'V_y',...
% 'D',...
% 'SAL',...
% 'TEMP',...
% 'WQ_NCS_SS1',...
% 'WQ_NCS_SS2',...
% 'WQ_NCS_SS3',...
% 'WQ_TRC_AGE',...
% 'WQ_OXY_OXY',...
% 'WQ_SIL_RSI',...
% 'WQ_NIT_AMM',...
% 'WQ_NIT_NIT',...
% 'WQ_PHS_FRP',...
% 'WQ_PHS_FRP_ADS',...
% 'WQ_OGM_DOC',...
% 'WQ_OGM_POC',...
% 'WQ_OGM_DON',...
% 'WQ_OGM_PON',...
% 'WQ_OGM_DOP',...
% 'WQ_OGM_POP',...
% 'WQ_PHY_GRN',...
% 'WQ_DIAG_TOT_TN',...
% 'WQ_DIAG_TOT_TP',...
% 'WQ_DIAG_TOT_TOC',...
% 'WQ_DIAG_TOT_TSS',...
% 'WQ_DIAG_TOT_TURBIDITY',...
% 'WQ_DIAG_SDG_OXY01',...
% 'WQ_DIAG_SDG_AMM01',...
% 'WQ_DIAG_SDG_POML01',...
% 'WQ_DIAG_SDG_SWI_DEFF',...
% 'WQ_DIAG_SDG_OPD',...
% 'WQ_DIAG_SDG_ARPD',...
% 'WQ_DIAG_SDG_FOM',...
% 'WQ_DIAG_SDG_TOC',...
% 'WQ_DIAG_SDG_TFE',...
% 'WQ_DIAG_SDG_TN',...
% 'WQ_DIAG_SDG_TP',...
% 'WQ_DIAG_SDG_TS',...
% 'WQ_DIAG_SDG_CRS',...
% 'WQ_DIAG_SDG_MINERL',...
% 'WQ_DIAG_SDG_AEROBIC',...
% 'WQ_DIAG_SDG_ANAEROBIC',...
% 'WQ_DIAG_SDG_DENIT',...
% 'WQ_DIAG_SDG_MNRED',...
% 'WQ_DIAG_SDG_FERED',...
% 'WQ_DIAG_SDG_SO4RED',...
% 'WQ_DIAG_SDG_METHAN',...
% 'WQ_DIAG_SDG_BPP',...
% 'WQ_DIAG_SDG_BIODEPTH',...
% 'WQ_DIAG_SDG_POROSITY',...
% 'WQ_DIAG_SDG_STEADINESS',...
% 'WQ_DIAG_SDG_ERROR',...
% 'WQ_MA2_ULVA',...
% 'WQ_MA2_ULVA_IN',...
% 'WQ_MA2_ULVA_IP',...
% 'WQ_DIAG_SDF_FSED_OXY',...
% 'WQ_DIAG_SDF_FSED_DIC',...
% 'WQ_DIAG_SDF_FSED_AMM',...
% 'WQ_DIAG_SDF_FSED_NIT',...
% 'WQ_DIAG_SDF_FSED_FRP',...
% 'WQ_DIAG_SDF_FSED_POC',...
% 'WQ_DIAG_SDF_FSED_DOC',...
% 'WQ_DIAG_SDF_FSED_PON',...
% 'WQ_DIAG_SDF_FSED_DON',...
% 'WQ_DIAG_SDF_FSED_POP',...
% 'WQ_DIAG_SDF_FSED_DOP',...
% 'WQ_DIAG_MAC_PAR',...
% 'WQ_DIAG_MAC_GPP',...
% 'WQ_DIAG_MAC_P_R',...
% 'WQ_DIAG_MAC_MAC',...
% 'WQ_DIAG_MAC_LAI',...
% 'WQ_DIAG_MAC_MAC_AG',...
% 'WQ_DIAG_MAC_MAC_BG',...
% 'WQ_DIAG_NCS_SS1_VVEL',...
% 'WQ_DIAG_NCS_SS2_VVEL',...
% 'WQ_DIAG_NCS_SS3_VVEL',...
% 'WQ_DIAG_NCS_SS_SED',...
% 'WQ_DIAG_NCS_TAU_0',...
% 'WQ_DIAG_NCS_EPSILON',...
% 'WQ_DIAG_NCS_FS1',...
% 'WQ_DIAG_NCS_FS2',...
% 'WQ_DIAG_NCS_FS3',...
% 'WQ_DIAG_NCS_SWI_DZ',...
% 'WQ_DIAG_NCS_RESUS',...
% 'WQ_DIAG_NCS_D_TAUB',...
% 'WQ_DIAG_OXY_SAT',...
% 'WQ_DIAG_OXY_SED_OXY',...
% 'WQ_DIAG_OXY_ATM_OXY_FLUX',...
% 'WQ_DIAG_OXY_SED_OXY_FLUX3D',...
% 'WQ_DIAG_OXY_ATM_OXY_FLUX3D',...
% 'WQ_DIAG_SIL_SED_RSI',...
% 'WQ_DIAG_NIT_SED_AMM',...
% 'WQ_DIAG_NIT_SED_NIT',...
% 'WQ_DIAG_NIT_NITRIF',...
% 'WQ_DIAG_NIT_DENIT',...
% 'WQ_DIAG_NIT_ANAMMOX',...
% 'WQ_DIAG_NIT_DNRA',...
% 'WQ_DIAG_NIT_ATM_DIN_FLUX',...
% 'WQ_DIAG_PHS_SED_FRP',...
% 'WQ_DIAG_PHS_ATM_DIP_FLUX',...
% 'WQ_DIAG_OGM_PSED_POC',...
% 'WQ_DIAG_OGM_PSED_PON',...
% 'WQ_DIAG_OGM_PSED_POP',...
% 'WQ_DIAG_OGM_SED_OM_FRAC',...
% 'WQ_DIAG_OGM_CDOM',...
% 'WQ_DIAG_OGM_SED_TOC',...
% 'WQ_DIAG_OGM_SED_TON',...
% 'WQ_DIAG_OGM_SED_TOP',...
% 'WQ_DIAG_OGM_SWI_POC',...
% 'WQ_DIAG_OGM_SWI_DOC',...
% 'WQ_DIAG_OGM_SWI_PON',...
% 'WQ_DIAG_OGM_SWI_DON',...
% 'WQ_DIAG_OGM_SWI_POP',...
% 'WQ_DIAG_OGM_SWI_DOP',...
% 'WQ_DIAG_OGM_POC_RESUS',...
% 'WQ_DIAG_OGM_PON_RESUS',...
% 'WQ_DIAG_OGM_POP_RESUS',...
% 'WQ_DIAG_OGM_POC_HYDROL',...
% 'WQ_DIAG_OGM_PON_HYDROL',...
% 'WQ_DIAG_OGM_POP_HYDROL',...
% 'WQ_DIAG_OGM_DOC_MINER',...
% 'WQ_DIAG_OGM_DON_MINER',...
% 'WQ_DIAG_OGM_DOP_MINER',...
% 'WQ_DIAG_OGM_ANAEROBIC',...
% 'WQ_DIAG_OGM_DENIT',...
% 'WQ_DIAG_OGM_BOD5',...
% 'WQ_DIAG_OGM_POM_VVEL',...
% 'WQ_DIAG_PHY_GRN_NTOP',...
% 'WQ_DIAG_PHY_GRN_FI',...
% 'WQ_DIAG_PHY_GRN_FNIT',...
% 'WQ_DIAG_PHY_GRN_FPHO',...
% 'WQ_DIAG_PHY_GRN_FSIL',...
% 'WQ_DIAG_PHY_GRN_FT',...
% 'WQ_DIAG_PHY_GRN_FSAL',...
% 'WQ_DIAG_PHY_GRN_GPP_C',...
% 'WQ_DIAG_PHY_GRN_RSP_C',...
% 'WQ_DIAG_PHY_GRN_EXC_C',...
% 'WQ_DIAG_PHY_GRN_MOR_C',...
% 'WQ_DIAG_PHY_GRN_SED_C',...
% 'WQ_DIAG_PHY_GRN_GPP_N',...
% 'WQ_DIAG_PHY_GRN_RSP_N',...
% 'WQ_DIAG_PHY_GRN_EXC_N',...
% 'WQ_DIAG_PHY_GRN_MOR_N',...
% 'WQ_DIAG_PHY_GRN_SED_N',...
% 'WQ_DIAG_PHY_GRN_GPP_P',...
% 'WQ_DIAG_PHY_GRN_RSP_P',...
% 'WQ_DIAG_PHY_GRN_EXC_P',...
% 'WQ_DIAG_PHY_GRN_MOR_P',...
% 'WQ_DIAG_PHY_GRN_SED_P',...
% 'WQ_DIAG_PHY_PSED_PHY',...
% 'WQ_DIAG_PHY_RESUS',...
% 'WQ_DIAG_PHY_TCHLA',...
% 'WQ_DIAG_PHY_IN',...
% 'WQ_DIAG_PHY_IP',...
% 'WQ_DIAG_PHY_GPP',...
% 'WQ_DIAG_PHY_NCP',...
% 'WQ_DIAG_PHY_NUP_NO3',...
% 'WQ_DIAG_PHY_NUP_NH4',...
% 'WQ_DIAG_PHY_PUP',...
% 'WQ_DIAG_PHY_CUP',...
% 'WQ_DIAG_PHY_PAR',...
% 'WQ_DIAG_PHY_TPHYS',...
% 'WQ_DIAG_PHY_PPR',...
% 'WQ_DIAG_PHY_NPR',...
% 'WQ_DIAG_PHY_MPB',...
% 'WQ_DIAG_PHY_BPP',...
% 'WQ_DIAG_PHY_BCP',...
% 'WQ_DIAG_PHY_MPBV',...
% 'WQ_DIAG_MA2_ULVA_NTOP',...
% 'WQ_DIAG_MA2_ULVA_FI',...
% 'WQ_DIAG_MA2_ULVA_FNIT',...
% 'WQ_DIAG_MA2_ULVA_FPHO',...
% 'WQ_DIAG_MA2_ULVA_FSIL',...
% 'WQ_DIAG_MA2_ULVA_FT',...
% 'WQ_DIAG_MA2_ULVA_FSAL',...
% 'WQ_DIAG_MA2_ULVA_FI_BEN',...
% 'WQ_DIAG_MA2_ULVA_FNIT_BEN',...
% 'WQ_DIAG_MA2_ULVA_FPHO_BEN',...
% 'WQ_DIAG_MA2_ULVA_FT_BEN',...
% 'WQ_DIAG_MA2_ULVA_FSAL_BEN',...
% 'WQ_DIAG_MA2_TMALG',...
% 'WQ_DIAG_MA2_IN',...
% 'WQ_DIAG_MA2_IP',...
% 'WQ_DIAG_MA2_MAG_BEN',...
% 'WQ_DIAG_MA2_IP_BEN',...
% 'WQ_DIAG_MA2_IN_BEN',...
% 'WQ_DIAG_MA2_GPP',...
% 'WQ_DIAG_MA2_PUP',...
% 'WQ_DIAG_MA2_NUP',...
% 'WQ_DIAG_MA2_NMP',...
% 'WQ_DIAG_MA2_GPP_BEN',...
% 'WQ_DIAG_MA2_NMP_BEN',...
% 'WQ_DIAG_MA2_HSI',...
% 'WQ_DIAG_MA2_PAR',...
% 'WQ_DIAG_MA2_EXTC',...
% 'WVHT'};
varname = {'WQ_DIAG_SDG_OXY01',...
'WQ_DIAG_SDG_AMM01',...
'WQ_DIAG_SDG_DOCL01',...
'WQ_DIAG_SDG_POML01',...
'WQ_DIAG_SDG_DOCR01',...
'WQ_DIAG_SDG_SWI_DEFF',...
'WQ_DIAG_SDG_OPD',...
'WQ_DIAG_SDG_ARPD',...
'WQ_DIAG_SDG_FOM',...
'WQ_DIAG_SDG_TOC',...
'WQ_DIAG_SDG_TFE',...
'WQ_DIAG_SDG_TN',...
'WQ_DIAG_SDG_TP',...
'WQ_DIAG_SDG_TS',...
'WQ_DIAG_SDG_CRS',...
'WQ_DIAG_SDG_MINERL',...
'WQ_DIAG_SDG_AEROBIC',...
'WQ_DIAG_SDG_ANAEROBIC',...
'WQ_DIAG_SDG_DENIT',...
'WQ_DIAG_SDG_MNRED',...
'WQ_DIAG_SDG_FERED',...
'WQ_DIAG_SDG_SO4RED',...
'WQ_DIAG_SDG_METHAN',...
'WQ_DIAG_SDG_BPP',...
'WQ_DIAG_SDG_BIODEPTH',...
'WQ_DIAG_SDG_POROSITY',...
'WQ_DIAG_SDG_STEADINESS',...
'WQ_DIAG_SDG_ERROR',...
'D',...
'SAL',...
'TEMP',...
'WQ_NCS_SS1',...
'WQ_NCS_SS2',...
'WQ_NCS_SS3',...
'WQ_TRC_AGE',...
'WQ_OXY_OXY',...
'WQ_SIL_RSI',...
'WQ_NIT_AMM',...
'WQ_NIT_NIT',...
'WQ_PHS_FRP',...
'WQ_PHS_FRP_ADS',...
'WQ_OGM_DOC',...
'WQ_OGM_POC',...
'WQ_OGM_DON',...
'WQ_OGM_PON',...
'WQ_OGM_DOP',...
'WQ_OGM_POP',...
'WQ_PHY_GRN',...
'WQ_MA2_ULVA',...
'WQ_MA2_ULVA_IN',...
'WQ_MA2_ULVA_IP',...
'WQ_DIAG_SDF_FSED_OXY',...
'WQ_DIAG_SDF_FSED_DIC',...
'WQ_DIAG_SDF_FSED_AMM',...
'WQ_DIAG_SDF_FSED_NIT',...
'WQ_DIAG_SDF_FSED_FRP',...
'WQ_DIAG_SDF_FSED_POC',...
'WQ_DIAG_SDF_FSED_DOC',...
'WQ_DIAG_SDF_FSED_PON',...
'WQ_DIAG_SDF_FSED_DON',...
'WQ_DIAG_SDF_FSED_POP',...
'WQ_DIAG_SDF_FSED_DOP',...
'WQ_DIAG_MAC_PAR',...
'WQ_DIAG_MAC_GPP',...
'WQ_DIAG_MAC_P_R',...
'WQ_DIAG_MAC_MAC',...
'WQ_DIAG_MAC_LAI',...
'WQ_DIAG_MAC_MAC_AG',...
'WQ_DIAG_MAC_MAC_BG',...
'WQ_DIAG_NCS_SS1_VVEL',...
'WQ_DIAG_NCS_SS1_SET',...
'WQ_DIAG_NCS_SS2_VVEL',...
'WQ_DIAG_NCS_SS2_SET',...
'WQ_DIAG_NCS_SS3_VVEL',...
'WQ_DIAG_NCS_SS3_SET',...
'WQ_DIAG_NCS_SS_SED',...
'WQ_DIAG_NCS_TAU_0',...
'WQ_DIAG_NCS_EPSILON',...
'WQ_DIAG_NCS_FS1',...
'WQ_DIAG_NCS_FS2',...
'WQ_DIAG_NCS_FS3',...
'WQ_DIAG_NCS_SET',...
'WQ_DIAG_NCS_SWI',...
'WQ_DIAG_NCS_SWI_DZ',...
'WQ_DIAG_NCS_RESUS',...
'WQ_DIAG_NCS_D_TAUB',...
'WQ_DIAG_OXY_SAT',...
'WQ_DIAG_OXY_OXY_DSF',...
'WQ_DIAG_OXY_OXY_ATM',...
'WQ_DIAG_OXY_OXY_DSFV',...
'WQ_DIAG_OXY_OXY_ATMV',...
'WQ_DIAG_SIL_DSF_RSI',...
'WQ_DIAG_NIT_AMM_DSF',...
'WQ_DIAG_NIT_NIT_DSF',...
'WQ_DIAG_NIT_NITRIF',...
'WQ_DIAG_NIT_DENIT',...
'WQ_DIAG_NIT_ANAMMOX',...
'WQ_DIAG_NIT_DNRA',...
'WQ_DIAG_NIT_DIN_ATM',...
'WQ_DIAG_PHS_FRP_ADS_SET',...
'WQ_DIAG_PHS_FRP_ADS_RES',...
'WQ_DIAG_PHS_FRP_SRP',...
'WQ_DIAG_PHS_FRP_DSF',...
'WQ_DIAG_PHS_DIP_ATM',...
'WQ_DIAG_OGM_POC_SET',...
'WQ_DIAG_OGM_PON_SET',...
'WQ_DIAG_OGM_POP_SET',...
'WQ_DIAG_OGM_OM_SED_FRAC',...
'WQ_DIAG_OGM_CDOM',...
'WQ_DIAG_OGM_TOC_SED',...
'WQ_DIAG_OGM_TON_SED',...
'WQ_DIAG_OGM_TOP_SED',...
'WQ_DIAG_OGM_POC_SWI',...
'WQ_DIAG_OGM_DOC_SWI',...
'WQ_DIAG_OGM_PON_SWI',...
'WQ_DIAG_OGM_DON_SWI',...
'WQ_DIAG_OGM_POP_SWI',...
'WQ_DIAG_OGM_DOP_SWI',...
'WQ_DIAG_OGM_POC_RES',...
'WQ_DIAG_OGM_PON_RES',...
'WQ_DIAG_OGM_POP_RES',...
'WQ_DIAG_OGM_POC_HYD',...
'WQ_DIAG_OGM_PON_HYD',...
'WQ_DIAG_OGM_POP_HYD',...
'WQ_DIAG_OGM_DOC_MIN',...
'WQ_DIAG_OGM_DON_MIN',...
'WQ_DIAG_OGM_DOP_MIN',...
'WQ_DIAG_OGM_DOC_ANAEROBIC',...
'WQ_DIAG_OGM_DOC_DENIT',...
'WQ_DIAG_OGM_BOD5',...
'WQ_DIAG_OGM_POM_VVEL',...
'WQ_DIAG_PHY_GRN_NTOP',...
'WQ_DIAG_PHY_GRN_FI',...
'WQ_DIAG_PHY_GRN_FNIT',...
'WQ_DIAG_PHY_GRN_FPHO',...
'WQ_DIAG_PHY_GRN_FSIL',...
'WQ_DIAG_PHY_GRN_FT',...
'WQ_DIAG_PHY_GRN_FSAL',...
'WQ_DIAG_PHY_GRN_GPP_C',...
'WQ_DIAG_PHY_GRN_RSP_C',...
'WQ_DIAG_PHY_GRN_EXC_C',...
'WQ_DIAG_PHY_GRN_MOR_C',...
'WQ_DIAG_PHY_GRN_SET_C',...
'WQ_DIAG_PHY_GRN_GPP_N',...
'WQ_DIAG_PHY_GRN_RSP_N',...
'WQ_DIAG_PHY_GRN_EXC_N',...
'WQ_DIAG_PHY_GRN_MOR_N',...
'WQ_DIAG_PHY_GRN_SET_N',...
'WQ_DIAG_PHY_GRN_GPP_P',...
'WQ_DIAG_PHY_GRN_RSP_P',...
'WQ_DIAG_PHY_GRN_EXC_P',...
'WQ_DIAG_PHY_GRN_MOR_P',...
'WQ_DIAG_PHY_GRN_SET_P',...
'WQ_DIAG_PHY_SET',...
'WQ_DIAG_PHY_RES',...
'WQ_DIAG_PHY_TCHLA',...
'WQ_DIAG_PHY_IN',...
'WQ_DIAG_PHY_IP',...
'WQ_DIAG_PHY_GPP',...
'WQ_DIAG_PHY_NCP',...
'WQ_DIAG_PHY_UPT_NO3',...
'WQ_DIAG_PHY_UPT_NH4',...
'WQ_DIAG_PHY_UPT_N2',...
'WQ_DIAG_PHY_UPT_PO4',...
'WQ_DIAG_PHY_UPT_DIC',...
'WQ_DIAG_PHY_PAR',...
'WQ_DIAG_PHY_TPHY',...
'WQ_DIAG_PHY_PPR',...
'WQ_DIAG_PHY_NPR',...
'WQ_DIAG_PHY_MPB_BEN',...
'WQ_DIAG_PHY_MPB_GPP',...
'WQ_DIAG_PHY_MPB_RSP',...
'WQ_DIAG_PHY_MPB_SWI',...
'WQ_DIAG_MA2_ULVA_NTOP',...
'WQ_DIAG_MA2_ULVA_FI',...
'WQ_DIAG_MA2_ULVA_FNIT',...
'WQ_DIAG_MA2_ULVA_FPHO',...
'WQ_DIAG_MA2_ULVA_FSIL',...
'WQ_DIAG_MA2_ULVA_FT',...
'WQ_DIAG_MA2_ULVA_FSAL',...
'WQ_DIAG_MA2_ULVA_FI_BEN',...
'WQ_DIAG_MA2_ULVA_FNIT_BEN',...
'WQ_DIAG_MA2_ULVA_FPHO_BEN',...
'WQ_DIAG_MA2_ULVA_FT_BEN',...
'WQ_DIAG_MA2_ULVA_FSAL_BEN',...
'WQ_DIAG_MA2_TMALG',...
'WQ_DIAG_MA2_IN',...
'WQ_DIAG_MA2_IP',...
'WQ_DIAG_MA2_MAG_BEN',...
'WQ_DIAG_MA2_IP_BEN',...
'WQ_DIAG_MA2_IN_BEN',...
'WQ_DIAG_MA2_GPP',...
'WQ_DIAG_MA2_PUP',...
'WQ_DIAG_MA2_NUP',...
'WQ_DIAG_MA2_NMP',...
'WQ_DIAG_MA2_GPP_BEN',...
'WQ_DIAG_MA2_NMP_BEN',...
'WQ_DIAG_MA2_MAG_SWI_C',...
'WQ_DIAG_MA2_MAG_SWI_N',...
'WQ_DIAG_MA2_MAG_SWI_P',...
'WQ_DIAG_MA2_HSI',...
'WQ_DIAG_MA2_PAR',...
'WQ_DIAG_MA2_EXTC',...
'WQ_DIAG_TOT_TN',...
'WQ_DIAG_TOT_TP',...
'WQ_DIAG_TOT_TOC',...
'WQ_DIAG_TOT_TSS',...
'WQ_DIAG_TOT_TURBIDITY',...
'WVHT'};

for vvvv=1:length(varname)
def.cAxis(vvvv).value = [ ];
end
%def.cAxis(3).value = [0 150];
% ____________________________________________________________Configuration

start_plot_ID = 1;
% end_plot_ID = 4;
% PLOT Configuration_______________________________________________________
plottype = 'timeseries'; %timeseries or 'profile'

plotvalidation = true; % Add field data to figure (true or false)

plotdepth = {'surface'};  % Cell-array with either one or both
depth_range = [0.2 100];
validation_minmax = 0;

istitled = 1;
isylabel = 1;
islegend = 1;
isYlim   = 1;
isRange  = 1;
isRange_Bottom = 0;
Range_ALL = 1;

filetype = 'eps';
def.expected = 1; % plot expected WL

isFieldRange = 0;
fieldprctile = [10 90];

isHTML = 1;

yr = 2019;
def.datearray = datenum(yr,7:6:42,1);

%outputdirectory = './Timeseries_Basecase_June/RAW/';
%htmloutput = './Timeseries_Basecase_June/HTML/';
outputdirectory = '/AED/Development/matt/hchb_tfvaed_v2_calibration_z31_newSHP/plots31_SDG4_only/RAW/';
htmloutput = '/AED/Development/matt/hchb_tfvaed_v2_calibration_z31_newSHP/plots31_SDG4_only/HTML/';
% ____________________________________________________________Configuration





% Models___________________________________________________________________
%  ncfile(1).name = '/Projects2/CDM/hchb_tfvaed_v1_resuspension/output_sedIC5/output/hchb_wave_21901101_20210701_wq_v5_resuspension_sedIC_all.nc';
%  ncfile(1).symbol = {'-';'--'};
%  ncfile(1).colour = {[140,81,10]./255,[216,179,101]./255};% Surface and Bottom % Surface and Bottom
%  ncfile(1).legend = 'V1-5';
%  ncfile(1).translate = 1;
% 
%  ncfile(1).name = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/output_20220314_v5/hchb_21901101_20220101_Wave_4PFTs_all.nc';
% '/AED/Development/matt/hchb_tfvaed_v2_calibration_z31_newSHP/output_good/hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
% ncfile(1).name = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/output/hchb_21901101_20220101_Wave_4PFTs_all.nc';
%'/Projects2/CDM/hchb_tfvaed_v2_resuspension_z31_newSHP_2022/outputV1/hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
% '/Projects2/CDM/hchb_tfvaed_v2_resuspension_z31_newSHP/output_newBIN_v4_highMPB/hchb_wave_21901101_20210701_wq_v5_resuspension_all_v21_5.nc';
% '/Projects2/CDM/hchb_tfvaed_v2_resuspension_z31_newSHP/output_newBIN/hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
%  ncfile(1).symbol = {'-';'--'};
%  ncfile(1).colour = {[31,120,180]./255,[31,120,180]./255}; % Surface and Bottom
%  ncfile(1).legend = '4PFT';
%  ncfile(1).translate = 1;
%  
%  ncfile(2).name = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/output_matt/hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
%                           %'W:\CDM\hchb_tfvaed_v2_resuspension_z31_newSHP_2022\outputV2\hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
%  ncfile(2).symbol = {'-';'--'};
%  ncfile(2).colour = {[255,127,0]./255,[255,127,0]./255}; % Surface and Bottom
%  ncfile(2).legend = 'SDG1';
%  ncfile(2).translate = 1;
% % % 
%  ncfile(3).name = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/output_matt_SDG2/hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
%  ncfile(3).symbol = {'-';'--'};
%  ncfile(3).colour = {[106,61,154]./255,[106,61,154]./255}; % Surface and Bottom
%  ncfile(3).legend = 'SDG2';
%  ncfile(3).translate = 1;
% % 
 ncfile(1).name = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/output_matt_SDG4/hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
 ncfile(1).symbol = {'-';'--'};
 ncfile(1).colour = {[230,245,152]./255,[1,102,94]./255}; % Surface and Bottom
 ncfile(1).legend = 'SDG4';
 ncfile(1).translate = 1;
% 
%  ncfile(5).name = 'Y:/CIIP/Scenarios/phase1/SC07/CoorongBGC_SC07_pump_in_out_reverse_500_ML_d_dry_001_wq_all.nc';
%  ncfile(5).symbol = {'-';'--'};
%  ncfile(5).colour = {[153,213,148]./255,[1,102,94]./255}; % Surface and Bottom
%  ncfile(5).legend = 'SC07';
%  ncfile(5).translate = 1;
% 
%  

% ___________________________________________________________________Models



% Defaults_________________________________________________________________

% Makes start date, end date and datetick array
%def.datearray = datenum(yr,0def.datearray = datenum(yr,01:4:36,01);
%def.datearray = datenum(yr,1:12:96,01);

% yr = 2012;
% def.datearray = datenum(yr,01:01:04,01);

def.dateformat = 'mm/yyyy';
% Must have same number as variable to plot & in same order

def.dimensions = [20 8]; % Width & Height in cm

def.dailyave = 0; % 1 for daily average, 0 for off. Daily average turns off smoothing.
def.smoothfactor = 3; % Must be odd number (set to 3 if none)

def.fieldsymbol = {'.','.'}; % Cell with same number of levels
def.fieldcolour = {'m',[0.6 0.6 0.6]}; % Cell with same number of levels

def.font = 'Arial';

def.xlabelsize = 7;
def.ylabelsize = 7;
def.titlesize = 10;
def.legendsize = 6;
def.legendlocation = 'northeastoutside';

def.visible = 'off'; % on or off
