
 

% SITE Configuration_______________________________________________________
% fielddata_matfile = 'lowerlakes.mat';
% fielddata = 'lowerlakes';

fielddata_matfile = '..\..\..\CDM\scripts\modeltools\matfiles\lowerlakes.mat';
fielddata = 'lowerlakes';
%fielddata_matfile = 'lowerlakes.mat';
%fielddata = 'lowerlakes';
polygon_file = '..\..\..\CDM\scripts\modeltools\gis\Coorong\Ruppia_Zones.shp';

%polygon_file = '.\GDSTN_Polygons_200m_v2_C3.shp';

%sites = [17,18,20];  % Sites in shapefile (polygon IDs) to plot
% ____________________________________________________________Configuration



% VAR Configuration________________________________________________________
varname = {...
 'SAL',...
'TEMP',...
% 'WQ_NCS_SS1',...
% 'WQ_TRC_AGE',...
% 'WQ_OXY_OXY',...
% 'WQ_SIL_RSI',...
% 'WQ_NIT_AMM',...
% 'WQ_NIT_NIT',...
% 'WQ_PHS_FRP',...
% 'WQ_PHS_FRP_ADS',...
% 'WQ_OGM_DOC',...
% 'WQ_OGM_POC',...
% 'WQ_OGM_DON',...
% 'WQ_OGM_PON',...
% 'WQ_OGM_DOP',...
% 'WQ_OGM_POP',...
% 'WQ_PHY_GRN',...
% 'WQ_MA2_ULVA',...
% 'WQ_MA2_ULVA_IN',...
% 'WQ_MA2_ULVA_IP',...
% 'WQ_DIAG_SDF_FSED_OXY',...
% 'WQ_DIAG_SDF_FSED_AMM',...
% 'WQ_DIAG_SDF_FSED_NIT',...
% 'WQ_DIAG_SDF_FSED_FRP',...
% 'WQ_DIAG_MAC_PAR',...
% 'WQ_DIAG_MAC_GPP',...
% 'WQ_DIAG_MAC_P_R',...
% 'WQ_DIAG_MAC_MAC',...
% 'WQ_DIAG_MAC_LAI',...
% 'WQ_DIAG_MAC_MAC_AG',...
% 'WQ_DIAG_MAC_MAC_BG',...
% 'WQ_DIAG_NCS_SS1_VVEL',...
% 'WQ_DIAG_NCS_SS_SED',...
% 'WQ_DIAG_NCS_TAU_0',...
% 'WQ_DIAG_NCS_EPSILON',...
% 'WQ_DIAG_NCS_FS1',...
% 'WQ_DIAG_NCS_SWI_DZ',...
% 'WQ_DIAG_NCS_RESUS',...
% 'WQ_DIAG_NCS_D_TAUB',...
% 'WQ_DIAG_OXY_SAT',...
% 'WQ_DIAG_OXY_SED_OXY',...
% 'WQ_DIAG_OXY_ATM_OXY_FLUX',...
% 'WQ_DIAG_SIL_SED_RSI',...
% 'WQ_DIAG_NIT_SED_AMM',...
% 'WQ_DIAG_NIT_SED_NIT',...
% 'WQ_DIAG_NIT_NITRIF',...
% 'WQ_DIAG_NIT_DENIT',...
% 'WQ_DIAG_NIT_ANAMMOX',...
% 'WQ_DIAG_NIT_DNRA',...
% 'WQ_DIAG_NIT_ATM_DIN_FLUX',...
% 'WQ_DIAG_PHS_SED_FRP',...
% 'WQ_DIAG_PHS_ATM_DIP_FLUX',...
% 'WQ_DIAG_OGM_PSED_POC',...
% 'WQ_DIAG_OGM_PSED_PON',...
% 'WQ_DIAG_OGM_PSED_POP',...
% 'WQ_DIAG_OGM_CDOM',...
% 'WQ_DIAG_PHY_GRN_NTOP',...
% 'WQ_DIAG_PHY_GRN_FI',...
% 'WQ_DIAG_PHY_GRN_FNIT',...
% 'WQ_DIAG_PHY_GRN_FPHO',...
% 'WQ_DIAG_PHY_GRN_FSIL',...
% 'WQ_DIAG_PHY_GRN_FT',...
% 'WQ_DIAG_PHY_GRN_FSAL',...
% 'WQ_DIAG_PHY_PSED_PHY',...
% 'WQ_DIAG_PHY_GPP',...
% 'WQ_DIAG_PHY_NCP',...
% 'WQ_DIAG_PHY_PPR',...
% 'WQ_DIAG_PHY_NPR',...
% 'WQ_DIAG_PHY_NUP_NO3',...
% 'WQ_DIAG_PHY_NUP_NH4',...
% 'WQ_DIAG_PHY_PUP',...
% 'WQ_DIAG_PHY_CUP',...
% 'WQ_DIAG_PHY_PAR',...
% 'WQ_DIAG_PHY_TCHLA',...
% 'WQ_DIAG_PHY_TPHYS',...
% 'WQ_DIAG_PHY_IN',...
% 'WQ_DIAG_PHY_IP',...
% 'WQ_DIAG_PHY_MPB',...
% 'WQ_DIAG_PHY_BPP',...
% 'WQ_DIAG_PHY_BCP',...
% 'WQ_DIAG_PHY_MPBV',...
% 'WQ_DIAG_MA2_ULVA_NTOP',...
% 'WQ_DIAG_MA2_ULVA_FI',...
% 'WQ_DIAG_MA2_ULVA_FNIT',...
% 'WQ_DIAG_MA2_ULVA_FPHO',...
% 'WQ_DIAG_MA2_ULVA_FSIL',...
% 'WQ_DIAG_MA2_ULVA_FT',...
% 'WQ_DIAG_MA2_ULVA_FSAL',...
% 'WQ_DIAG_MA2_ULVA_FI_BEN',...
% 'WQ_DIAG_MA2_ULVA_FNIT_BEN',...
% 'WQ_DIAG_MA2_ULVA_FPHO_BEN',...
% 'WQ_DIAG_MA2_ULVA_FT_BEN',...
% 'WQ_DIAG_MA2_ULVA_FSAL_BEN',...
% 'WQ_DIAG_MA2_TMALG',...
% 'WQ_DIAG_MA2_IN',...
% 'WQ_DIAG_MA2_IP',...
% 'WQ_DIAG_MA2_MAG_BEN',...
% 'WQ_DIAG_MA2_IP_BEN',...
% 'WQ_DIAG_MA2_IN_BEN',...
% 'WQ_DIAG_MA2_GPP',...
% 'WQ_DIAG_MA2_PUP',...
% 'WQ_DIAG_MA2_NUP',...
% 'WQ_DIAG_MA2_NMP',...
% 'WQ_DIAG_MA2_GPP_BEN',...
% 'WQ_DIAG_MA2_NMP_BEN',...
% 'WQ_DIAG_MA2_HSI',...
% 'WQ_DIAG_MA2_PAR',...
% 'WQ_DIAG_MA2_EXTC',...
% 'WQ_DIAG_HAB_RUPPIA_HSI',...
% 'WQ_DIAG_HAB_RUPPIA_HSI_PLANT',...
% 'WQ_DIAG_HAB_WETTIME',...
% 'WQ_DIAG_HAB_DRYTIME',...
% 'WQ_DIAG_TOT_TN',...
% 'WQ_DIAG_TOT_TP',...
% 'WQ_DIAG_TOT_TOC',...
% 'WQ_DIAG_TOT_TSS',...
% 'WQ_DIAG_TOT_TURBIDITY',...
};


for vvvv=1:length(varname)
def.cAxis(vvvv).value = [ ];
end
% ____________________________________________________________Configuration

start_plot_ID = 1;
%end_plot_ID = 13;
% PLOT Configuration_______________________________________________________
plottype = 'timeseries'; %timeseries or 'profile'

plotvalidation = true; % Add field data to figure (true or false)

plotdepth = {'surface'};%;'bottom'};  % Cell-array with either one or both
depth_range = [0.2 100];
validation_minmax = 0;

add_error = 1;


istitled = 1;
isylabel = 1;
islegend = 1;
isYlim   = 1;
isRange  = 0;
isRange_Bottom = 0;
Range_ALL = 0;

filetype = 'eps';
def.expected = 1; % plot expected WL

isFieldRange = 0;
fieldprctile = [10 90];

isHTML = 1;

yr = 2017;
def.datearray = datenum(yr,7:3:20,01);

%outputdirectory = './Timeseries_Basecase_June/RAW/';
%htmloutput = './Timeseries_Basecase_June/HTML/';
outputdirectory = 'C:\Users\00065525\Scratch\CDM\mettest\Images\WINBIN/RAW/';
htmloutput = 'C:\Users\00065525\Scratch\CDM\mettest\Images\WINBIN/HTML/';
% ____________________________________________________________Configuration





% Models___________________________________________________________________
 ncfile(1).name = 'C:\Users\00065525\Scratch\CDM\mettest\CoorongBGC_006_validation_201707_201903_wq_met_all.nc';
 ncfile(1).symbol = {'-';'--'};
 ncfile(1).colour = {[140,81,10]./255,[216,179,101]./255};% Surface and Bottom % Surface and Bottom
 ncfile(1).legend = 'Met';
 ncfile(1).translate = 1;
% 
 ncfile(2).name = 'C:\Users\00065525\Scratch\CDM\mettest\CoorongBGC_006_validation_201707_201903_wq_all.nc';
 ncfile(2).symbol = {'-';'--'};
 ncfile(2).colour = {[252,141,89]./255,[1,102,94]./255}; % Surface and Bottom
 ncfile(2).legend = 'BASE CASE';
 ncfile(2).translate = 1;
% 
 ncfile(3).name = 'C:\Users\00065525\Scratch\CDM\mettest\CoorongBGC_006_validation_201707_201903_wq_met_wind_all.nc';
 ncfile(3).symbol = {'-';'--'};
 ncfile(3).colour = {[254,224,139]./255,[1,102,94]./255}; % Surface and Bottom
 ncfile(3).legend = 'Met & Wind field';
 ncfile(3).translate = 1;
% 
%  ncfile(4).name = 'Y:\CIIP\Scenarios\phase1\SC05\CoorongBGC_SC05_SEFA_dry_001_wq_all.nc';
%  ncfile(4).symbol = {'-';'--'};
%  ncfile(4).colour = {[230,245,152]./255,[1,102,94]./255}; % Surface and Bottom
%  ncfile(4).legend = 'SC05';
%  ncfile(4).translate = 1;
% 
%  ncfile(5).name = 'Y:\CIIP\Scenarios\phase1\SC07\CoorongBGC_SC07_pump_in_out_reverse_500_ML_d_dry_001_wq_all.nc';
%  ncfile(5).symbol = {'-';'--'};
%  ncfile(5).colour = {[153,213,148]./255,[1,102,94]./255}; % Surface and Bottom
%  ncfile(5).legend = 'SC07';
%  ncfile(5).translate = 1;
% 
%  

% ___________________________________________________________________Models



% Defaults_________________________________________________________________

% Makes start date, end date and datetick array
%def.datearray = datenum(yr,0def.datearray = datenum(yr,01:4:36,01);
%def.datearray = datenum(yr,1:12:96,01);

% yr = 2012;
% def.datearray = datenum(yr,01:01:04,01);

def.dateformat = 'dd/mm';
% Must have same number as variable to plot & in same order

def.dimensions = [20 8]; % Width & Height in cm

def.dailyave = 0; % 1 for daily average, 0 for off. Daily average turns off smoothing.
def.smoothfactor = 3; % Must be odd number (set to 3 if none)

def.fieldsymbol = {'.','.'}; % Cell with same number of levels
def.fieldcolour = {'m',[0.6 0.6 0.6]}; % Cell with same number of levels

def.font = 'Arial';

def.xlabelsize = 7;
def.ylabelsize = 7;
def.titlesize = 10;
def.legendsize = 6;
def.legendlocation = 'northeastoutside';

def.visible = 'off'; % on or off
