


% SITE Configuration_______________________________________________________
% fielddata_matfile = 'lowerlakes.mat';
% fielddata = 'lowerlakes';

fielddata_matfile = '/Projects2/busch_github/CDM/data/store/archive/cllmm.mat';
%fielddata = 'UA';
fielddata = 'cllmm';
%polygon_file = '../../../CDM/gis/supplementary/Coorong/Coorong_obs_sites.shp';
%polygon_file = '../../../CDM/gis/supplementary/Coorong_IC_regions.shp';
polygon_file = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/model/gis/shp/31_material_zones_names.shp';

%sites = [5:23];  % Sites in shapefile (polygon IDs) to plot
% ____________________________________________________________Configuration



varname = {'WQ_OXY_OXY',...
'WQ_PHS_FRP',...
'WQ_PHS_FRP_ADS',...
'WQ_DIAG_TOT_TP',...
'WQ_DIAG_TOT_TOC',...
'WQ_DIAG_TOT_TSS',...
'WQ_DIAG_TOT_TURBIDITY',...
'WQ_OGM_DOC',...
'WQ_OGM_POC',...
'WQ_OGM_PON',...
'WQ_DIAG_MAG_ULVA_A_C2P_BEN',...
'WQ_DIAG_MAG_ULVA_A_C2N_BEN',...
'WQ_DIAG_MAG_GPP_BEN',...
'WQ_DIAG_MAG_MAG_SWI_N',...
'WQ_DIAG_MAG_MAG_SWI_P',...
'WQ_DIAG_MAG_ULVA_A_FT_BEN',...
'WQ_DIAG_MAG_ULVA_A_FSAL_BEN',...
'WQ_DIAG_MAG_ULVA_A_C2P_BEN',...
'WQ_DIAG_MAG_ULVA_A_C2N_BEN',...
'WQ_DIAG_MAG_ULVA_A_FI_BEN',...
'WQ_DIAG_MAG_PARC',...
'WQ_DIAG_MAG_HGTC',...
'WQ_DIAG_MAG_EXTC',...
'WQ_DIAG_MAG_ULVA_B_FI_BEN',...
'WQ_DIAG_MAG_ULVA_C_FI_BEN',...
'WQ_DIAG_MAG_ULVA_B_FNIT_BEN',...
'WQ_DIAG_MAG_MAG_BEN',...
'WQ_DIAG_MAG_IP_BEN',...
'WQ_DIAG_MAG_IN_BEN',...
'WQ_NIT_AMM',...
'WQ_NIT_NIT',...
'WQ_DIAG_PHY_TCHLA',...
'WQ_DIAG_PHY_MPB_BEN',...
'WQ_DIAG_OGM_DON_SWI',...
'WQ_DIAG_MAG_MAG_BEN',...
'WQ_DIAG_TOT_TN',...
'WQ_DIAG_OGM_DOC_FLOC',...
'WQ_DIAG_MAG_ULVA_A_N2P_BEN',...
'WQ_DIAG_MAG_ULVA_B_C2P_BEN',...
'WQ_DIAG_MAG_ULVA_B_C2N_BEN',...
'WQ_DIAG_MAG_ULVA_B_N2P_BEN',...
'WQ_DIAG_MAG_ULVA_C_C2P_BEN',...
'WQ_DIAG_MAG_ULVA_C_C2N_BEN',...
'WQ_DIAG_MAG_ULVA_C_N2P_BEN',...
'WQ_DIAG_MAG_ULVA_C_C2P',...
'WQ_DIAG_MAG_ULVA_C_C2N',...
'WQ_DIAG_MAG_ULVA_C_N2P',...
'WQ_DIAG_MAG_GPP_BEN',...
'WQ_DIAG_MAG_RSP_BEN',...
'WQ_DIAG_MAG_PUP_BEN',...
'WQ_DIAG_MAG_NUP_BEN',...
'WQ_DIAG_MAG_NMP_BEN',...
'WQ_DIAG_PHY_PHY_SWI_C',...
'WQ_DIAG_PHY_PHY_SWI_N',...
'WQ_DIAG_PHY_PHY_SWI_P',...
'WQ_DIAG_PHY_MPB_BEN',...
'WQ_DIAG_PHY_MPB_GPP',...
'WQ_DIAG_PHY_MPB_RSP',...
'WQ_DIAG_PHY_MPB_XNC',...
'WQ_DIAG_PHY_MPB_XPC',...
'WQ_DIAG_MAG_TMALG',...
'WQ_MAG_ULVA_C',...
'WQ_DIAG_MAG_ULVA_A_FNIT_BEN',...
'WQ_DIAG_MAG_ULVA_A_FPHO_BEN',...
'WQ_DIAG_MAG_MAG_SWI_C',...
'WQ_DIAG_MAG_SLG_BEN',...
'WQ_DIAG_MAG_PUP_BEN',...
'WQ_DIAG_MAG_NUP_BEN',...
'WQ_DIAG_MAG_NMP_BEN',...
'WQ_DIAG_MAG_GPP_BEN',...
'WQ_DIAG_MAG_RSP_BEN',...
'WQ_DIAG_MAG_ULVA_B_FPHO_BEN',...
'WQ_DIAG_MAG_ULVA_B_FT_BEN',...
'WQ_DIAG_MAG_ULVA_B_FSAL_BEN',...
'WQ_DIAG_MAG_ULVA_C_FNIT_BEN',...
'WQ_DIAG_MAG_ULVA_C_FPHO_BEN',...
'WQ_DIAG_MAG_ULVA_C_FT_BEN',...
'WQ_DIAG_MAG_ULVA_C_FSAL_BEN',...
'WQ_DIAG_MAG_ULVA_C_FI',...
'WQ_DIAG_MAG_ULVA_C_FNIT',...
'WQ_DIAG_MAG_ULVA_C_FPHO',...
'WQ_DIAG_MAG_ULVA_C_FT',...
'WQ_DIAG_MAG_ULVA_C_FSAL',...
'WQ_NIT_AMM',...
'WQ_NIT_NIT',...
'WQ_DIAG_MAG_IN',...
'WQ_DIAG_MAG_IP',...
'WQ_DIAG_MAG_GPP',...
'WQ_DIAG_MAG_PUP',...
'WQ_DIAG_MAG_NUP',...
'WQ_DIAG_MAG_NMP',...
'WQ_DIAG_MAG_HSI',...
'WQ_OGM_DON',...
'WQ_DIAG_OGM_DON_SWI',...
'WQ_NIT_NIT',...
'WQ_DIAG_PHY_MPB_BEN',...
'WQ_DIAG_PHY_UPT_NO3',...
'WQ_DIAG_TOT_TN',...
'WQ_OGM_PON',...
'WQ_NIT_AMM',...
'WQ_DIAG_PHY_UPT_NH4',...
'WQ_DIAG_NIT_AMM_DSF',...
'WQ_DIAG_NIT_NIT_DSF',...
'WQ_DIAG_NIT_NITRIF',...
'WQ_DIAG_NIT_DENIT',...
'WQ_DIAG_OGM_PON_SWI',...
'WQ_DIAG_OGM_POC_SWI',...
'WQ_DIAG_OGM_DOC_SWI',...
'WQ_DIAG_OGM_POP_SWI',...
'WQ_DIAG_OGM_DOP_SWI',...
'WQ_DIAG_PHY_TCHLA',...
'WQ_DIAG_OGM_DOC_FLOC',...
'WQ_OXY_OXY',...
'WQ_DIAG_NIT_ANAMMOX',...
'WQ_DIAG_NIT_DNRA',...
'WQ_PHS_FRP',...
'WQ_PHS_FRP_ADS',...
'WQ_DIAG_TOT_TP',...
'WQ_DIAG_TOT_TOC',...
'WQ_DIAG_TOT_TSS',...
'WQ_DIAG_TOT_TURBIDITY',...
'WQ_OGM_DOC',...
'WQ_OGM_POC',...
'WQ_OGM_DOP',...
'WQ_OGM_POP',...
'WQ_PHY_GRN',...
'WQ_PHY_CRYPT',...
'WQ_PHY_DIATOM',...
'WQ_PHY_DINO',...
'WVHT'};

for vvvv=1:length(varname)
def.cAxis(vvvv).value = [ ];
end
%def.cAxis(3).value = [0 150];
% ____________________________________________________________Configuration

start_plot_ID = 1;
% end_plot_ID = 4;
% PLOT Configuration_______________________________________________________
plottype = 'timeseries'; %timeseries or 'profile'

plotvalidation = true; % Add field data to figure (true or false)

plotdepth = {'surface'};  % Cell-array with either one or both
depth_range = [0.2 100];
validation_minmax = 0;

istitled = 1;
isylabel = 1;
islegend = 1;
isYlim   = 1;
isRange  = 1;
isRange_Bottom = 0;
Range_ALL = 1;
add_error = 0;

filetype = 'eps';
def.expected = 1; % plot expected WL

isFieldRange = 0;
fieldprctile = [10 90];

isHTML = 1;

yr = 2017;
def.datearray = datenum(yr,7:6:65,1); %55

%outputdirectory = './Timeseries_Basecase_June/RAW/';
%htmloutput = './Timeseries_Basecase_June/HTML/';
outputdirectory = '/AED/Development/matt/hchb_tfvaed_v3_2022_4PFTs_SedZone_sdg/plots31_MAG_eWater_07June_a/RAW/';
htmloutput = '/AED/Development/matt/hchb_tfvaed_v3_2022_4PFTs_SedZone_sdg/plots31_MAG_eWater_07June_a/HTML/';
% ____________________________________________________________Configuration





% Models___________________________________________________________________

 ncfile(2).name = '/Scratch/MER_Coorong_eWater_2022_GEN15_newBC_testing/output_basecase_mag5a/eWater2021_basecase_t3_all.nc';
 ncfile(2).symbol = {'-';'--'};
 ncfile(2).colour = {[106,61,154]./255,[106,61,154]./255}; % Surface and Bottom
 ncfile(2).legend = 'mag06';
 ncfile(2).translate = 1;
 ncfile(1).name = '/Scratch/MER_Coorong_eWater_2022_GEN15_newBC_testing/output_basecase_mag4/eWater2021_basecase_t3_all.nc';
 ncfile(1).symbol = {'-';'--'};
 ncfile(1).colour = {[230,245,152]./255,[1,102,94]./255}; % Surface and Bottom
 ncfile(1).legend = 'mag04';
 ncfile(1).translate = 1;

 ncfile(3).name = '/Projects2/CDM/output_basecase_hd/eWater2021_basecase_t3_all.nc';
 ncfile(3).symbol = {'-';'--'};
 ncfile(3).colour = {[153,213,148]./255,[1,102,94]./255}; % Surface and Bottom
 ncfile(3).legend = 'sdg';
 ncfile(3).translate = 1;


% % %
%  ncfile(4).name = '/Projects2/CDM/hchb_tfvaed_v3_2022_4PFTs/output_matt_SDG3/hchb_wave_21901101_20210701_wq_v5_resuspension_all.nc';
%  ncfile(4).symbol = {'-';'--'};
%  ncfile(4).colour = {[230,245,152]./255,[1,102,94]./255}; % Surface and Bottom
%  ncfile(4).legend = 'SDG3';
%  ncfile(4).translate = 1;
%
%  ncfile(5).name = 'Y:/CIIP/Scenarios/phase1/SC07/CoorongBGC_SC07_pump_in_out_reverse_500_ML_d_dry_001_wq_all.nc';
%  ncfile(5).symbol = {'-';'--'};
%  ncfile(5).colour = {[153,213,148]./255,[1,102,94]./255}; % Surface and Bottom
%  ncfile(5).legend = 'SC07';
%  ncfile(5).translate = 1;
%
%

% ___________________________________________________________________Models



% Defaults_________________________________________________________________

% Makes start date, end date and datetick array
%def.datearray = datenum(yr,0def.datearray = datenum(yr,01:4:36,01);
%def.datearray = datenum(yr,1:12:96,01);

% yr = 2012;
% def.datearray = datenum(yr,01:01:04,01);

def.dateformat = 'mm/yyyy';
% Must have same number as variable to plot & in same order

def.dimensions = [20 8]; % Width & Height in cm

def.dailyave = 0; % 1 for daily average, 0 for off. Daily average turns off smoothing.
def.smoothfactor = 3; % Must be odd number (set to 3 if none)

def.fieldsymbol = {'.','.'}; % Cell with same number of levels
def.fieldcolour = {'m',[0.6 0.6 0.6]}; % Cell with same number of levels

def.font = 'Arial';

def.xlabelsize = 7;
def.ylabelsize = 7;
def.titlesize = 10;
def.legendsize = 6;
def.legendlocation = 'northeastoutside';

def.visible = 'off'; % on or off
