%% Main code to run CopyScnFigures %%
ScriptDir = 'C:\Users\sqn\Documents\20210902_FiguresToCopy_EIS_ScenarioReport\';

ListOfScenario = {'Scn05_Scn02_Scn00_DRY',...
    'Scn05_Scn02_Scn00_WET',...
    'Scn06_Scn04_Scn00_DRY',...
    'Scn06_Scn04_Scn00_WET',...
    'Scn07_Scn01_Scn00_DRY',...
    'Scn07_Scn01_Scn00_WET',...
    'Scn08_Scn03_Scn00_DRY',...
    'Scn08_Scn03_Scn00_WET',...
    'Scn09_Scn01_Scn00_DRY',...
    'Scn09_Scn01_Scn00_WET'};

ListOfScnNames = {'Scenario 05 - dry year',...
    'Scenario 05 - wet year',...
    'Scenario 06 - dry year',...
    'Scenario 06 - wet year',...
    'Scenario 07 - dry year',...
    'Scenario 07 - wet year',...
    'Scenario 08 - dry year',...
    'Scenario 08 - wet year',...
    'Scenario 09 - dry year',...
    'Scenario 09 - wet year'};

for i = 1:size(ListOfScenario,2)
    run_CopyScnFigures_SC(ListOfScenario{i},ListOfScnNames{i});
    cd(ScriptDir);
end
    